### ISSUE TITLE
feat: 친구가 한 명이 아닌 여러 명이 들어가도록 수정

### ISSUE THREAD

**Issue by sootudio** [seoul-night/sodam-server#14]
### 작업 개요
- 현재 친구가 한 명만 들어갈 수 있는데, 여러 명이 들어가도록 수정

### 작업 내용
- 친구 entity 변경
- 친구 추가, 조회, 삭제 API 수정
- 위치 조회 API 수정

### Todo list
- [ ] 친구 entity와 response body들 변경
- [ ] 친구 추가 API에서 PUT이 아닌 POST를 사용, 친구를 추가하면 배열에 추가되도록 수정.
- [ ] 친구 조회 API에서 단일 조회가 아닌, 리스트로 조회를 하도록 수정
- [ ] 친구 삭제를 할 때, Pathvariable로 삭제할 친구 id 보내도록 수정
- [ ] 위치 조회 시, 친구 리스트의 맨 처음 값을 조회하도록 수정
