### ISSUE TITLE
feat: 위치 데이터 저장 API

### ISSUE THREAD

**Issue by jaejunlee11** [seoul-night/sodam-server#4]
### 작업 개요
- 위치 데이터 저장/조회 API 개발

### 작업 내용
- 위치 데이터 저장 DB 생성
- 위치 데이터 저장 기능 개발
- 위치 데이터 조회 기능 개발

### Todo list
- [x] 위치 데이터 저장 DB 생성
- [x] location 도메인 생성 및 post 기능 개발
- [x] GET 기능 개발
