### ISSUE TITLE
feat: 등록 장소 데이터 관리 API

### ISSUE THREAD

**Issue by jaejunlee11** [seoul-night/sodam-server#6]
### 작업 개요
- 등록 장소 데이터 관리 API 개발

### 작업 내용
- 장소 등록 DB 생성
- 장소 등록 기능 구현
- 등록 장소 리스트 조회 기능 구현
- 등록 장소 제거 기능 구현

### Todo list
- [x] 장소 등록 DB 생성
- [ ] 장소 등록 API 생성
- [ ] 장소 리스트 조회 API 생성
- [ ] 장소 제거 API 생성
